int signalbox() {
   Int_t Upsilon4S_B_mu_mcErrors;
   Int_t Upsilon4S_B_mcErrors;
   Float_t Upsilon4S_B_useCMSFrame__bop__bc;
   Float_t Upsilon4S_B_deltae;
   Float_t Upsilon4S_B_mbc;
   Float_t Upsilon4S_B_ThrustB;
   Float_t Upsilon4S_B_ThrustO;
   Float_t Upsilon4S_B_CosTBTO;
   Float_t Upsilon4S_B_CosTBz;
   Float_t Upsilon4S_B_R2;
   Float_t Upsilon4S_B_cc1_CcROE;
   Float_t Upsilon4S_B_cc2_CcROE;
   Float_t Upsilon4S_B_cc3_CcROE;
   Float_t Upsilon4S_B_cc4_CcROE;
   Float_t Upsilon4S_B_cc5_CcROE;
   Float_t Upsilon4S_B_cc6_CcROE;
   Float_t Upsilon4S_B_cc7_CcROE;
   Float_t Upsilon4S_B_cc8_CcROE;
   Float_t Upsilon4S_B_cc9_CcROE;
   Float_t Upsilon4S_B_cc1;
   Float_t Upsilon4S_B_cc2;
   Float_t Upsilon4S_B_cc3;
   Float_t Upsilon4S_B_cc4;
   Float_t Upsilon4S_B_cc5;
   Float_t Upsilon4S_B_cc6;
   Float_t Upsilon4S_B_cc7;
   Float_t Upsilon4S_B_cc8;
   Float_t Upsilon4S_B_cc9;
   Float_t Upsilon4S_B_mm2;
   Float_t Upsilon4S_B_et;
   Float_t Upsilon4S_B_hso00;
   Float_t Upsilon4S_B_hso01;
   Float_t Upsilon4S_B_hso02;
   Float_t Upsilon4S_B_hso03;
   Float_t Upsilon4S_B_hso04;
   Float_t Upsilon4S_B_hso10;
   Float_t Upsilon4S_B_hso12;
   Float_t Upsilon4S_B_hso14;
   Float_t Upsilon4S_B_hso20;
   Float_t Upsilon4S_B_hso22;
   Float_t Upsilon4S_B_hso24;
   Float_t Upsilon4S_B_hoo0;
   Float_t Upsilon4S_B_hoo1;
   Float_t Upsilon4S_B_hoo2;
   Float_t Upsilon4S_B_hoo3;
   Float_t Upsilon4S_B_hoo4;
   Float_t Upsilon4S_B_mu_kaonID;
   Float_t isSignal;
   Float_t weight;


   TFile *file1 = new TFile("test.root");
   TTree *t1 = (TTree*)file1->Get("y4s");
   t1->SetBranchAddress("isSignal",&isSignal);
   t1->SetBranchAddress("useCMSFrameLPdaughterLP1COpRPRP",&Upsilon4S_B_useCMSFrame__bop__bc);
   t1->SetBranchAddress("deltaE",&Upsilon4S_B_deltae);
   t1->SetBranchAddress("Mbc",&Upsilon4S_B_mbc);
   t1->SetBranchAddress("ThrustB",&Upsilon4S_B_ThrustB);
   t1->SetBranchAddress("ThrustO",&Upsilon4S_B_ThrustO);
   t1->SetBranchAddress("CosTBTO",&Upsilon4S_B_CosTBTO);
   t1->SetBranchAddress("CosTBz",&Upsilon4S_B_CosTBz);
   t1->SetBranchAddress("R2",&Upsilon4S_B_R2);
   t1->SetBranchAddress("CleoConeLP1COROERP",&Upsilon4S_B_cc1_CcROE);
   t1->SetBranchAddress("CleoConeLP2COROERP",&Upsilon4S_B_cc2_CcROE);
   t1->SetBranchAddress("CleoConeLP3COROERP",&Upsilon4S_B_cc3_CcROE);
   t1->SetBranchAddress("CleoConeLP4COROERP",&Upsilon4S_B_cc4_CcROE);
   t1->SetBranchAddress("CleoConeLP5COROERP",&Upsilon4S_B_cc5_CcROE);
   t1->SetBranchAddress("CleoConeLP6COROERP",&Upsilon4S_B_cc6_CcROE);
   t1->SetBranchAddress("CleoConeLP7COROERP",&Upsilon4S_B_cc7_CcROE);
   t1->SetBranchAddress("CleoConeLP8COROERP",&Upsilon4S_B_cc8_CcROE);
   t1->SetBranchAddress("CleoConeLP9COROERP",&Upsilon4S_B_cc9_CcROE);
   t1->SetBranchAddress("CleoConeLP1RP",&Upsilon4S_B_cc1);
   t1->SetBranchAddress("CleoConeLP2RP",&Upsilon4S_B_cc2);
   t1->SetBranchAddress("CleoConeLP3RP",&Upsilon4S_B_cc3);
   t1->SetBranchAddress("CleoConeLP4RP",&Upsilon4S_B_cc4);
   t1->SetBranchAddress("CleoConeLP5RP",&Upsilon4S_B_cc5);
   t1->SetBranchAddress("CleoConeLP6RP",&Upsilon4S_B_cc6);
   t1->SetBranchAddress("CleoConeLP7RP",&Upsilon4S_B_cc7);
   t1->SetBranchAddress("CleoConeLP8RP",&Upsilon4S_B_cc8);
   t1->SetBranchAddress("CleoConeLP9RP",&Upsilon4S_B_cc9);
   t1->SetBranchAddress("KSFWVariablesLPmm2RP",&Upsilon4S_B_mm2);
   t1->SetBranchAddress("KSFWVariablesLPetRP",&Upsilon4S_B_et);
   t1->SetBranchAddress("KSFWVariablesLPhso00RP",&Upsilon4S_B_hso00);
   t1->SetBranchAddress("KSFWVariablesLPhso01RP",&Upsilon4S_B_hso01);
   t1->SetBranchAddress("KSFWVariablesLPhso02RP",&Upsilon4S_B_hso02);
   t1->SetBranchAddress("KSFWVariablesLPhso03RP",&Upsilon4S_B_hso03);
   t1->SetBranchAddress("KSFWVariablesLPhso04RP",&Upsilon4S_B_hso04);
   t1->SetBranchAddress("KSFWVariablesLPhso10RP",&Upsilon4S_B_hso10);
   t1->SetBranchAddress("KSFWVariablesLPhso12RP",&Upsilon4S_B_hso12);
   t1->SetBranchAddress("KSFWVariablesLPhso14RP",&Upsilon4S_B_hso14);
   t1->SetBranchAddress("KSFWVariablesLPhso20RP",&Upsilon4S_B_hso20);
   t1->SetBranchAddress("KSFWVariablesLPhso22RP",&Upsilon4S_B_hso22);
   t1->SetBranchAddress("KSFWVariablesLPhso24RP",&Upsilon4S_B_hso24);
   t1->SetBranchAddress("KSFWVariablesLPhoo0RP",&Upsilon4S_B_hoo0);
   t1->SetBranchAddress("KSFWVariablesLPhoo1RP",&Upsilon4S_B_hoo1);
   t1->SetBranchAddress("KSFWVariablesLPhoo2RP",&Upsilon4S_B_hoo2);
   t1->SetBranchAddress("KSFWVariablesLPhoo3RP",&Upsilon4S_B_hoo3);
   t1->SetBranchAddress("KSFWVariablesLPhoo4RP",&Upsilon4S_B_hoo4);
   t1->SetBranchAddress("daughtersLP0COkaonIDRP",&Upsilon4S_B_mu_kaonID);
   t1->SetBranchAddress("weight",&weight);

   TFile *newfile = new TFile("testbox.root","recreate");
   TTree *te = new TTree("y4s","y4s");
   te->Branch("isSignal",&isSignal);
   te->Branch("useCMSFrameLPdaughterLP1COpRPRP",&Upsilon4S_B_useCMSFrame__bop__bc);
   te->Branch("deltaE",&Upsilon4S_B_deltae);
   te->Branch("Mbc",&Upsilon4S_B_mbc);
   te->Branch("ThrustB",&Upsilon4S_B_ThrustB);
   te->Branch("ThrustO",&Upsilon4S_B_ThrustO);
   te->Branch("CosTBTO",&Upsilon4S_B_CosTBTO);
   te->Branch("CosTBz",&Upsilon4S_B_CosTBz);
   te->Branch("R2",&Upsilon4S_B_R2);
   te->Branch("CleoConeLP1COROERP",&Upsilon4S_B_cc1_CcROE);
   te->Branch("CleoConeLP2COROERP",&Upsilon4S_B_cc2_CcROE);
   te->Branch("CleoConeLP3COROERP",&Upsilon4S_B_cc3_CcROE);
   te->Branch("CleoConeLP4COROERP",&Upsilon4S_B_cc4_CcROE);
   te->Branch("CleoConeLP5COROERP",&Upsilon4S_B_cc5_CcROE);
   te->Branch("CleoConeLP6COROERP",&Upsilon4S_B_cc6_CcROE);
   te->Branch("CleoConeLP7COROERP",&Upsilon4S_B_cc7_CcROE);
   te->Branch("CleoConeLP8COROERP",&Upsilon4S_B_cc8_CcROE);
   te->Branch("CleoConeLP9COROERP",&Upsilon4S_B_cc9_CcROE);
   te->Branch("CleoConeLP1RP",&Upsilon4S_B_cc1);
   te->Branch("CleoConeLP2RP",&Upsilon4S_B_cc2);
   te->Branch("CleoConeLP3RP",&Upsilon4S_B_cc3);
   te->Branch("CleoConeLP4RP",&Upsilon4S_B_cc4);
   te->Branch("CleoConeLP5RP",&Upsilon4S_B_cc5);
   te->Branch("CleoConeLP6RP",&Upsilon4S_B_cc6);
   te->Branch("CleoConeLP7RP",&Upsilon4S_B_cc7);
   te->Branch("CleoConeLP8RP",&Upsilon4S_B_cc8);
   te->Branch("CleoConeLP9RP",&Upsilon4S_B_cc9);
   te->Branch("KSFWVariablesLPmm2RP",&Upsilon4S_B_mm2);
   te->Branch("KSFWVariablesLPetRP",&Upsilon4S_B_et);
   te->Branch("KSFWVariablesLPhso00RP",&Upsilon4S_B_hso00);
   te->Branch("KSFWVariablesLPhso01RP",&Upsilon4S_B_hso01);
   te->Branch("KSFWVariablesLPhso02RP",&Upsilon4S_B_hso02);
   te->Branch("KSFWVariablesLPhso03RP",&Upsilon4S_B_hso03);
   te->Branch("KSFWVariablesLPhso04RP",&Upsilon4S_B_hso04);
   te->Branch("KSFWVariablesLPhso10RP",&Upsilon4S_B_hso10);
   te->Branch("KSFWVariablesLPhso12RP",&Upsilon4S_B_hso12);
   te->Branch("KSFWVariablesLPhso14RP",&Upsilon4S_B_hso14);
   te->Branch("KSFWVariablesLPhso20RP",&Upsilon4S_B_hso20);
   te->Branch("KSFWVariablesLPhso22RP",&Upsilon4S_B_hso22);
   te->Branch("KSFWVariablesLPhso24RP",&Upsilon4S_B_hso24);
   te->Branch("KSFWVariablesLPhoo0RP",&Upsilon4S_B_hoo0);
   te->Branch("KSFWVariablesLPhoo1RP",&Upsilon4S_B_hoo1);
   te->Branch("KSFWVariablesLPhoo2RP",&Upsilon4S_B_hoo2);
   te->Branch("KSFWVariablesLPhoo3RP",&Upsilon4S_B_hoo3);
   te->Branch("KSFWVariablesLPhoo4RP",&Upsilon4S_B_hoo4);
   te->Branch("daughtersLP0COkaonIDRP",&Upsilon4S_B_mu_kaonID);
   te->Branch("weight",&weight);
   for (i=0;i<t1->GetEntries();i++) {
      t1->GetEntry(i);
      if (Upsilon4S_B_useCMSFrame__bop__bc>2.45&&Upsilon4S_B_useCMSFrame__bop__bc<2.85)
         te->Fill();
   }
   te->Write();
   newfile->Close();
   return 0;
}
